Repository fonzdm/servarr, pull requests merged in 2024-07, with the labels that each got.

#48 Add tags to provide different deployment scenarios
  servarr/Chart.yaml
  servarr/README.md
  servarr/values.yaml
Labels: enhancement

#51 Update Truecharts Repo URL
  servarr/Chart.yaml
  servarr/README.md
Labels: bug

#52 Update Truechart Repo URL in CICD Config
  .github/workflows/release.yaml
Labels: bug, ci
