Repository fonzdm/servarr, pull requests merged in 2024-04, with the labels that each got.

#14 Add the (Automated) Chart Documentation
  .github/workflows/helm-docs.yaml
  .pre-commit-config.yaml
  README.md
  servarr/.helmignore
  servarr/README.md
  servarr/README.md.gotmpl
  servarr/values.yaml
Labels: documentation

#18 Fix storage class name variable
  servarr/templates/pvc.yaml
Labels: bug

#20 Torrent credential handling
  servarr/README.md
  servarr/config/qbittorrent/init-qbittorrent.py
  servarr/config/qbittorrent/qBittorrent.conf
  servarr/templates/configmaps.yaml
  servarr/templates/pre-deployment-job.yaml
  servarr/templates/secret.yaml
  servarr/values.yaml
Labels: enhancement

#23 fix prowlarr api for qbittorrent registration
  servarr/templates/init-downloaders.yaml
Labels: bug

#24 Refactor services init jobs
  servarr/README.md
  servarr/config/scripts/init-jellyfin.py
  servarr/config/scripts/init-jellyseerr.py
  servarr/config/scripts/init-prowlarr.py
  servarr/config/scripts/init-qbittorrent.py
  servarr/config/scripts/init-radarr.py
  servarr/config/scripts/init-sonarr.py
  servarr/templates/add-indexers-prowlarr.yaml
  servarr/templates/configmaps.yaml
  servarr/templates/init-downloaders.yaml
  servarr/templates/init-jellyfin.yaml
  servarr/templates/init-jellyseerr.yaml
  servarr/templates/init-prowlarr.yaml
  servarr/templates/init-radarr.yaml
  servarr/templates/init-sonarr.yaml
  servarr/templates/pre-deployment-job.yaml
  servarr/values.yaml
Labels: enhancement

#28 Fix Unauthorized error when providing default credentials
  servarr/README.md
  servarr/config/scripts/init-qbittorrent.py
  servarr/values.yaml
Labels: bug
