Repository fonzdm/servarr, pull requests merged in 2024-05, with the labels that each got.

#30 Add the Helm Chart post installation notes
  servarr/templates/NOTES.txt
Labels: enhancement

#31 Add `global.ingressClassName` anchor without default value
  .github/ci/ci-values.yaml
  servarr/README.md
  servarr/values.yaml
Labels: enhancement

#32 Add a pipeline to manage stale issues/PRs
  .github/ci/stale-detector-bot.yaml
Labels: enhancement, ci

#33 move the stale action in workflows
  .github/workflows/stale-detector-bot.yaml
Labels: ci

#35 Add a pipeline to automate chart release
  .github/ci/cr.yaml
  .github/workflows/release.yaml
  README.md
Labels: enhancement, ci

#41 Add Helm annotations for ArtifactHub integration
  README.md
  servarr/Chart.yaml
Labels: enhancement

#45 use h4 instead of unordered list
  .github/pull_request_template.md
Labels: enhancement

#46 Split lint and build actions in two different pipelines
  .github/workflows/chart-build.yaml
  .github/workflows/chart-lint.yaml
Labels: ci
