Repository fonzdm/servarr, pull requests merged in 2025-02, with the labels that each got.

#59 Remove `issuer` parameters from the values
  servarr/README.md
  servarr/templates/secret.yaml
  servarr/values.yaml
Labels: bug

#69 Introduce cache usage in both build and lint pipeline
  .github/workflows/chart-build.yaml
  .github/workflows/chart-lint.yaml
Labels: ci

#70 Revert Helm Lint workflow rule
  .github/workflows/chart-lint.yaml
Labels: ci

#65 Fix the init jobs to run also on ARM devices
  servarr/config/scripts/init-qbittorrent.py
  servarr/templates/init-jellyfin.yaml
  servarr/templates/init-jellyseerr.yaml
  servarr/templates/init-prowlarr.yaml
  servarr/templates/init-radarr.yaml
  servarr/templates/init-sonarr.yaml
  servarr/templates/pre-deployment-job.yaml
Labels: enhancement
